#!/usr/bin/bash
#
# This file is in the Public Domain.
#
# Authors: Hans Petter Jansson <hpj@copyleft.no>, Daniel Playfair Cal <daniel.playfair.cal@gmail.com>

set +e


SESSIONDIR="$HOME/.gdb-session"
DATE=`date +%y-%m-%d_%H-%M-%S`
LOG_NAME="$SESSIONDIR/$DATE"

mkdir -p "$SESSIONDIR"

export G_SLICE=always-malloc
export G_DEBUG=gc-friendly

gdbserver localhost:3000 /usr/bin/gnome-shell "$@"

echo "$?" > "$LOG_NAME.exitcode"
